-- Comprehensive Skills and Categories Expansion
-- Adding hundreds of relevant skills for South African job market

-- Insert comprehensive skills across expanded categories
INSERT INTO public.skills (name, category) VALUES

-- Programming & Development
('HTML', 'Programming & Development'),
('CSS', 'Programming & Development'),
('JavaScript', 'Programming & Development'),
('TypeScript', 'Programming & Development'),
('React', 'Programming & Development'),
('Vue.js', 'Programming & Development'),
('Angular', 'Programming & Development'),
('Node.js', 'Programming & Development'),
('Express.js', 'Programming & Development'),
('Next.js', 'Programming & Development'),
('Python', 'Programming & Development'),
('Django', 'Programming & Development'),
('Flask', 'Programming & Development'),
('Java', 'Programming & Development'),
('Spring Boot', 'Programming & Development'),
('C#', 'Programming & Development'),
('.NET', 'Programming & Development'),
('PHP', 'Programming & Development'),
('Laravel', 'Programming & Development'),
('Ruby', 'Programming & Development'),
('Ruby on Rails', 'Programming & Development'),
('Go', 'Programming & Development'),
('Rust', 'Programming & Development'),
('Swift', 'Programming & Development'),
('Kotlin', 'Programming & Development'),
('Flutter', 'Programming & Development'),
('React Native', 'Programming & Development'),
('iOS Development', 'Programming & Development'),
('Android Development', 'Programming & Development'),
('Git', 'Programming & Development'),
('GitHub', 'Programming & Development'),
('Docker', 'Programming & Development'),
('Kubernetes', 'Programming & Development'),
('AWS', 'Programming & Development'),
('Azure', 'Programming & Development'),
('Google Cloud', 'Programming & Development'),
('DevOps', 'Programming & Development'),
('CI/CD', 'Programming & Development'),
('REST APIs', 'Programming & Development'),
('GraphQL', 'Programming & Development'),
('Microservices', 'Programming & Development'),
('Agile Development', 'Programming & Development'),
('Scrum', 'Programming & Development'),
('Test-Driven Development', 'Programming & Development'),
('Unit Testing', 'Programming & Development'),
('Integration Testing', 'Programming & Development'),

-- Data & Analytics
('SQL', 'Data & Analytics'),
('MySQL', 'Data & Analytics'),
('PostgreSQL', 'Data & Analytics'),
('MongoDB', 'Data & Analytics'),
('Redis', 'Data & Analytics'),
('Data Analysis', 'Data & Analytics'),
('Data Visualization', 'Data & Analytics'),
('Power BI', 'Data & Analytics'),
('Tableau', 'Data & Analytics'),
('Excel Advanced', 'Data & Analytics'),
('Google Analytics', 'Data & Analytics'),
('R Programming', 'Data & Analytics'),
('Python for Data Science', 'Data & Analytics'),
('Pandas', 'Data & Analytics'),
('NumPy', 'Data & Analytics'),
('Matplotlib', 'Data & Analytics'),
('Seaborn', 'Data & Analytics'),
('Jupyter Notebooks', 'Data & Analytics'),
('Machine Learning', 'Data & Analytics'),
('Deep Learning', 'Data & Analytics'),
('TensorFlow', 'Data & Analytics'),
('PyTorch', 'Data & Analytics'),
('Scikit-learn', 'Data & Analytics'),
('Statistics', 'Data & Analytics'),
('Predictive Analytics', 'Data & Analytics'),
('Business Intelligence', 'Data & Analytics'),
('ETL Processes', 'Data & Analytics'),
('Data Mining', 'Data & Analytics'),
('Big Data', 'Data & Analytics'),
('Apache Spark', 'Data & Analytics'),
('Hadoop', 'Data & Analytics'),

-- Digital Marketing & Social Media
('Digital Marketing', 'Digital Marketing & Social Media'),
('Social Media Marketing', 'Digital Marketing & Social Media'),
('Content Marketing', 'Digital Marketing & Social Media'),
('SEO', 'Digital Marketing & Social Media'),
('SEM', 'Digital Marketing & Social Media'),
('Google Ads', 'Digital Marketing & Social Media'),
('Facebook Ads', 'Digital Marketing & Social Media'),
('Instagram Marketing', 'Digital Marketing & Social Media'),
('LinkedIn Marketing', 'Digital Marketing & Social Media'),
('Twitter Marketing', 'Digital Marketing & Social Media'),
('TikTok Marketing', 'Digital Marketing & Social Media'),
('YouTube Marketing', 'Digital Marketing & Social Media'),
('Email Marketing', 'Digital Marketing & Social Media'),
('Marketing Automation', 'Digital Marketing & Social Media'),
('CRM Systems', 'Digital Marketing & Social Media'),
('HubSpot', 'Digital Marketing & Social Media'),
('Salesforce', 'Digital Marketing & Social Media'),
('Google Analytics', 'Digital Marketing & Social Media'),
('Conversion Rate Optimization', 'Digital Marketing & Social Media'),
('A/B Testing', 'Digital Marketing & Social Media'),
('Influencer Marketing', 'Digital Marketing & Social Media'),
('Affiliate Marketing', 'Digital Marketing & Social Media'),
('Brand Management', 'Digital Marketing & Social Media'),
('Public Relations', 'Digital Marketing & Social Media'),
('Copywriting', 'Digital Marketing & Social Media'),
('Content Creation', 'Digital Marketing & Social Media'),

-- Design & Creative
('Graphic Design', 'Design & Creative'),
('UI/UX Design', 'Design & Creative'),
('Web Design', 'Design & Creative'),
('Mobile App Design', 'Design & Creative'),
('Adobe Photoshop', 'Design & Creative'),
('Adobe Illustrator', 'Design & Creative'),
('Adobe InDesign', 'Design & Creative'),
('Adobe XD', 'Design & Creative'),
('Figma', 'Design & Creative'),
('Sketch', 'Design & Creative'),
('Canva', 'Design & Creative'),
('Logo Design', 'Design & Creative'),
('Brand Identity', 'Design & Creative'),
('Typography', 'Design & Creative'),
('Color Theory', 'Design & Creative'),
('Layout Design', 'Design & Creative'),
('Print Design', 'Design & Creative'),
('Packaging Design', 'Design & Creative'),
('Motion Graphics', 'Design & Creative'),
('Video Editing', 'Design & Creative'),
('Adobe Premiere Pro', 'Design & Creative'),
('Adobe After Effects', 'Design & Creative'),
('Final Cut Pro', 'Design & Creative'),
('Photography', 'Design & Creative'),
('Photo Editing', 'Design & Creative'),
('3D Modeling', 'Design & Creative'),
('Blender', 'Design & Creative'),
('AutoCAD', 'Design & Creative'),
('SketchUp', 'Design & Creative'),

-- Business & Management
('Project Management', 'Business & Management'),
('Agile Project Management', 'Business & Management'),
('Scrum Master', 'Business & Management'),
('Product Management', 'Business & Management'),
('Business Analysis', 'Business & Management'),
('Strategic Planning', 'Business & Management'),
('Operations Management', 'Business & Management'),
('Supply Chain Management', 'Business & Management'),
('Quality Management', 'Business & Management'),
('Risk Management', 'Business & Management'),
('Change Management', 'Business & Management'),
('Team Leadership', 'Business & Management'),
('People Management', 'Business & Management'),
('Performance Management', 'Business & Management'),
('Stakeholder Management', 'Business & Management'),
('Vendor Management', 'Business & Management'),
('Budget Management', 'Business & Management'),
('Resource Planning', 'Business & Management'),
('Business Development', 'Business & Management'),
('Sales Management', 'Business & Management'),
('Customer Relationship Management', 'Business & Management'),
('Market Research', 'Business & Management'),
('Competitive Analysis', 'Business & Management'),
('SWOT Analysis', 'Business & Management'),
('Business Process Improvement', 'Business & Management'),
('Lean Management', 'Business & Management'),
('Six Sigma', 'Business & Management'),
('Microsoft Project', 'Business & Management'),
('Jira', 'Business & Management'),
('Trello', 'Business & Management'),
('Asana', 'Business & Management'),

-- Finance & Accounting
('Financial Analysis', 'Finance & Accounting'),
('Financial Modeling', 'Finance & Accounting'),
('Budgeting', 'Finance & Accounting'),
('Forecasting', 'Finance & Accounting'),
('Cost Accounting', 'Finance & Accounting'),
('Management Accounting', 'Finance & Accounting'),
('Financial Reporting', 'Finance & Accounting'),
('Tax Preparation', 'Finance & Accounting'),
('Audit', 'Finance & Accounting'),
('Bookkeeping', 'Finance & Accounting'),
('Accounts Payable', 'Finance & Accounting'),
('Accounts Receivable', 'Finance & Accounting'),
('Payroll Processing', 'Finance & Accounting'),
('Investment Analysis', 'Finance & Accounting'),
('Risk Assessment', 'Finance & Accounting'),
('Credit Analysis', 'Finance & Accounting'),
('Banking', 'Finance & Accounting'),
('Insurance', 'Finance & Accounting'),
('Compliance', 'Finance & Accounting'),
('IFRS', 'Finance & Accounting'),
('GAAP', 'Finance & Accounting'),
('SAP', 'Finance & Accounting'),
('QuickBooks', 'Finance & Accounting'),
('Sage', 'Finance & Accounting'),
('Xero', 'Finance & Accounting'),
('Excel Financial Modeling', 'Finance & Accounting'),

-- Healthcare & Medical
('Patient Care', 'Healthcare & Medical'),
('Medical Administration', 'Healthcare & Medical'),
('Healthcare Management', 'Healthcare & Medical'),
('Medical Coding', 'Healthcare & Medical'),
('Medical Billing', 'Healthcare & Medical'),
('Electronic Health Records', 'Healthcare & Medical'),
('HIPAA Compliance', 'Healthcare & Medical'),
('Clinical Research', 'Healthcare & Medical'),
('Pharmacy', 'Healthcare & Medical'),
('Nursing', 'Healthcare & Medical'),
('Physical Therapy', 'Healthcare & Medical'),
('Occupational Therapy', 'Healthcare & Medical'),
('Medical Laboratory', 'Healthcare & Medical'),
('Radiology', 'Healthcare & Medical'),
('Telemedicine', 'Healthcare & Medical'),
('Health Information Systems', 'Healthcare & Medical'),
('Public Health', 'Healthcare & Medical'),
('Epidemiology', 'Healthcare & Medical'),
('Health Education', 'Healthcare & Medical'),
('Mental Health', 'Healthcare & Medical'),

-- Engineering & Technical
('Mechanical Engineering', 'Engineering & Technical'),
('Electrical Engineering', 'Engineering & Technical'),
('Civil Engineering', 'Engineering & Technical'),
('Chemical Engineering', 'Engineering & Technical'),
('Industrial Engineering', 'Engineering & Technical'),
('Environmental Engineering', 'Engineering & Technical'),
('Mining Engineering', 'Engineering & Technical'),
('Petroleum Engineering', 'Engineering & Technical'),
('Aerospace Engineering', 'Engineering & Technical'),
('Biomedical Engineering', 'Engineering & Technical'),
('Computer Engineering', 'Engineering & Technical'),
('Network Engineering', 'Engineering & Technical'),
('Systems Engineering', 'Engineering & Technical'),
('Quality Assurance', 'Engineering & Technical'),
('Technical Writing', 'Engineering & Technical'),
('CAD Design', 'Engineering & Technical'),
('SolidWorks', 'Engineering & Technical'),
('MATLAB', 'Engineering & Technical'),
('LabVIEW', 'Engineering & Technical'),
('PLC Programming', 'Engineering & Technical'),
('SCADA Systems', 'Engineering & Technical'),
('Instrumentation', 'Engineering & Technical'),
('Maintenance', 'Engineering & Technical'),
('Troubleshooting', 'Engineering & Technical'),
('Safety Management', 'Engineering & Technical'),

-- Languages
('English', 'Languages'),
('Afrikaans', 'Languages'),
('Zulu', 'Languages'),
('Xhosa', 'Languages'),
('Sotho', 'Languages'),
('Tswana', 'Languages'),
('Pedi', 'Languages'),
('Venda', 'Languages'),
('Tsonga', 'Languages'),
('Ndebele', 'Languages'),
('Swati', 'Languages'),
('French', 'Languages'),
('German', 'Languages'),
('Portuguese', 'Languages'),
('Spanish', 'Languages'),
('Mandarin', 'Languages'),
('Arabic', 'Languages'),
('Hindi', 'Languages'),
('Sign Language', 'Languages'),

-- Soft Skills
('Communication', 'Soft Skills'),
('Public Speaking', 'Soft Skills'),
('Presentation Skills', 'Soft Skills'),
('Written Communication', 'Soft Skills'),
('Verbal Communication', 'Soft Skills'),
('Active Listening', 'Soft Skills'),
('Interpersonal Skills', 'Soft Skills'),
('Teamwork', 'Soft Skills'),
('Collaboration', 'Soft Skills'),
('Leadership', 'Soft Skills'),
('Team Leadership', 'Soft Skills'),
('Mentoring', 'Soft Skills'),
('Coaching', 'Soft Skills'),
('Problem Solving', 'Soft Skills'),
('Critical Thinking', 'Soft Skills'),
('Analytical Thinking', 'Soft Skills'),
('Creative Thinking', 'Soft Skills'),
('Decision Making', 'Soft Skills'),
('Time Management', 'Soft Skills'),
('Organization', 'Soft Skills'),
('Prioritization', 'Soft Skills'),
('Multitasking', 'Soft Skills'),
('Attention to Detail', 'Soft Skills'),
('Adaptability', 'Soft Skills'),
('Flexibility', 'Soft Skills'),
('Resilience', 'Soft Skills'),
('Stress Management', 'Soft Skills'),
('Emotional Intelligence', 'Soft Skills'),
('Empathy', 'Soft Skills'),
('Conflict Resolution', 'Soft Skills'),
('Negotiation', 'Soft Skills'),
('Customer Service', 'Soft Skills'),
('Cultural Awareness', 'Soft Skills'),
('Work Ethic', 'Soft Skills'),
('Initiative', 'Soft Skills'),
('Self-Motivation', 'Soft Skills'),
('Continuous Learning', 'Soft Skills'),

-- Sales & Customer Service
('Sales', 'Sales & Customer Service'),
('B2B Sales', 'Sales & Customer Service'),
('B2C Sales', 'Sales & Customer Service'),
('Inside Sales', 'Sales & Customer Service'),
('Outside Sales', 'Sales & Customer Service'),
('Retail Sales', 'Sales & Customer Service'),
('Account Management', 'Sales & Customer Service'),
('Lead Generation', 'Sales & Customer Service'),
('Cold Calling', 'Sales & Customer Service'),
('Sales Presentations', 'Sales & Customer Service'),
('Closing Techniques', 'Sales & Customer Service'),
('Customer Service', 'Sales & Customer Service'),
('Customer Support', 'Sales & Customer Service'),
('Help Desk', 'Sales & Customer Service'),
('Call Center', 'Sales & Customer Service'),
('Live Chat Support', 'Sales & Customer Service'),
('Customer Success', 'Sales & Customer Service'),
('Customer Retention', 'Sales & Customer Service'),
('Complaint Handling', 'Sales & Customer Service'),
('Upselling', 'Sales & Customer Service'),
('Cross-selling', 'Sales & Customer Service'),

-- Education & Training
('Teaching', 'Education & Training'),
('Curriculum Development', 'Education & Training'),
('Instructional Design', 'Education & Training'),
('E-Learning', 'Education & Training'),
('Training Delivery', 'Education & Training'),
('Adult Learning', 'Education & Training'),
('Educational Technology', 'Education & Training'),
('Assessment Design', 'Education & Training'),
('Learning Management Systems', 'Education & Training'),
('Tutoring', 'Education & Training'),
('Academic Writing', 'Education & Training'),
('Research', 'Education & Training'),
('Educational Psychology', 'Education & Training'),
('Special Education', 'Education & Training'),
('Early Childhood Education', 'Education & Training'),

-- Legal & Compliance
('Legal Research', 'Legal & Compliance'),
('Contract Law', 'Legal & Compliance'),
('Corporate Law', 'Legal & Compliance'),
('Employment Law', 'Legal & Compliance'),
('Intellectual Property', 'Legal & Compliance'),
('Compliance Management', 'Legal & Compliance'),
('Regulatory Affairs', 'Legal & Compliance'),
('Risk Assessment', 'Legal & Compliance'),
('Legal Writing', 'Legal & Compliance'),
('Litigation Support', 'Legal & Compliance'),
('Paralegal Skills', 'Legal & Compliance'),
('Document Review', 'Legal & Compliance'),
('Case Management', 'Legal & Compliance'),

-- Hospitality & Tourism
('Hotel Management', 'Hospitality & Tourism'),
('Restaurant Management', 'Hospitality & Tourism'),
('Event Planning', 'Hospitality & Tourism'),
('Tourism Management', 'Hospitality & Tourism'),
('Travel Planning', 'Hospitality & Tourism'),
('Guest Services', 'Hospitality & Tourism'),
('Food Service', 'Hospitality & Tourism'),
('Catering', 'Hospitality & Tourism'),
('Housekeeping Management', 'Hospitality & Tourism'),
('Front Office Operations', 'Hospitality & Tourism'),
('Revenue Management', 'Hospitality & Tourism'),
('Hospitality Marketing', 'Hospitality & Tourism'),

-- Agriculture & Environment
('Agriculture', 'Agriculture & Environment'),
('Crop Management', 'Agriculture & Environment'),
('Livestock Management', 'Agriculture & Environment'),
('Sustainable Farming', 'Agriculture & Environment'),
('Agricultural Technology', 'Agriculture & Environment'),
('Environmental Science', 'Agriculture & Environment'),
('Environmental Management', 'Agriculture & Environment'),
('Sustainability', 'Agriculture & Environment'),
('Climate Change', 'Agriculture & Environment'),
('Conservation', 'Agriculture & Environment'),
('Renewable Energy', 'Agriculture & Environment'),
('Waste Management', 'Agriculture & Environment'),
('Water Management', 'Agriculture & Environment'),

-- Emerging Technologies
('Artificial Intelligence', 'Emerging Technologies'),
('Machine Learning', 'Emerging Technologies'),
('Deep Learning', 'Emerging Technologies'),
('Natural Language Processing', 'Emerging Technologies'),
('Computer Vision', 'Emerging Technologies'),
('Blockchain', 'Emerging Technologies'),
('Cryptocurrency', 'Emerging Technologies'),
('Internet of Things', 'Emerging Technologies'),
('Cybersecurity', 'Emerging Technologies'),
('Information Security', 'Emerging Technologies'),
('Ethical Hacking', 'Emerging Technologies'),
('Penetration Testing', 'Emerging Technologies'),
('Cloud Computing', 'Emerging Technologies'),
('Edge Computing', 'Emerging Technologies'),
('Quantum Computing', 'Emerging Technologies'),
('Augmented Reality', 'Emerging Technologies'),
('Virtual Reality', 'Emerging Technologies'),
('Mixed Reality', 'Emerging Technologies'),
('Robotics', 'Emerging Technologies'),
('Automation', 'Emerging Technologies'),
('RPA (Robotic Process Automation)', 'Emerging Technologies'),
('5G Technology', 'Emerging Technologies'),

-- Manufacturing & Production
('Manufacturing', 'Manufacturing & Production'),
('Production Planning', 'Manufacturing & Production'),
('Quality Control', 'Manufacturing & Production'),
('Lean Manufacturing', 'Manufacturing & Production'),
('Supply Chain', 'Manufacturing & Production'),
('Inventory Management', 'Manufacturing & Production'),
('Logistics', 'Manufacturing & Production'),
('Warehouse Management', 'Manufacturing & Production'),
('Distribution', 'Manufacturing & Production'),
('Procurement', 'Manufacturing & Production'),
('Vendor Management', 'Manufacturing & Production'),
('Operations Research', 'Manufacturing & Production'),

-- Human Resources
('Human Resources', 'Human Resources'),
('Recruitment', 'Human Resources'),
('Talent Acquisition', 'Human Resources'),
('Employee Relations', 'Human Resources'),
('Performance Management', 'Human Resources'),
('Training & Development', 'Human Resources'),
('Compensation & Benefits', 'Human Resources'),
('HR Analytics', 'Human Resources'),
('Organizational Development', 'Human Resources'),
('Change Management', 'Human Resources'),
('Employee Engagement', 'Human Resources'),
('Diversity & Inclusion', 'Human Resources'),
('HR Information Systems', 'Human Resources'),
('Labor Relations', 'Human Resources'),
('Workplace Safety', 'Human Resources'),

-- Media & Communications
('Journalism', 'Media & Communications'),
('Broadcasting', 'Media & Communications'),
('Video Production', 'Media & Communications'),
('Audio Production', 'Media & Communications'),
('Podcasting', 'Media & Communications'),
('Content Writing', 'Media & Communications'),
('Technical Writing', 'Media & Communications'),
('Copywriting', 'Media & Communications'),
('Editing', 'Media & Communications'),
('Proofreading', 'Media & Communications'),
('Social Media Management', 'Media & Communications'),
('Digital Content Creation', 'Media & Communications'),
('SEO Writing', 'Media & Communications'),
('Grant Writing', 'Media & Communications'),
('Proposal Writing', 'Media & Communications')

-- Handle conflicts by updating existing skills if they already exist
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  created_at = COALESCE(public.skills.created_at, now());

